"""
create_archive_structure.py

Creates the archive/public_html/ directory structure mirroring orthodox.net,
with a README.md in each folder describing its contents.
"""

import os

BASE = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "archive", "public_html")

# Directory descriptions based on the live site's index pages and content
# Format: (dirname, file_count, size_mb, description, status)
# status: "placeholder" or "active"
DIRECTORIES = [
    ("10things", 40, 0.77,
     "Short teachings on various Orthodox Christian topics, formatted as '10 things to know' guides. Includes topics like preparation for Holy Communion, the genealogy of Christ, and saints' lives.",
     "placeholder"),
    ("6minutesorlessorthodoxvideos", 22, 0.08,
     "Short Orthodox Christian video content, six minutes or less in duration.",
     "placeholder"),
    ("a-fathers-letters", 24, 0.13,
     "Pastoral letters from Fr. Seraphim Holland to the parish, dating from 2001 onwards.",
     "placeholder"),
    ("a-little-bit", 16, 1.81,
     "Short devotional content — brief spiritual reflections and teachings.",
     "placeholder"),
    ("a-word-from-the-pastor", 23, 0.09,
     "Regular pastoral messages and words from the parish priest.",
     "placeholder"),
    ("aboutus", 127, 47.37,
     "Parish information for St. Nicholas Orthodox Church, McKinney, TX. Includes contact details, directions, clergy information, parish history, and testimony.",
     "placeholder"),
    ("akathists", 48, 64.32,
     "Akathist hymns — devotional poetic compositions used in Orthodox worship. Includes texts in English and Church Slavonic.",
     "placeholder"),
    ("announcements", 39, 3.65,
     "Parish announcements and bulletins.",
     "placeholder"),
    ("apostol", 28, 0.17,
     "Apostol readings — Epistle readings from the Acts of the Apostles and the Epistles used in Orthodox liturgical services.",
     "placeholder"),
    ("appeals", 27, 0.13,
     "Appeals and requests from the parish or related Orthodox organizations.",
     "placeholder"),
    ("articles", 295, 14.14,
     "Religious articles on Orthodox Christian theology, practice, and life. Includes essays by Fr. Seraphim Holland and other Orthodox authors.",
     "placeholder"),
    ("audio", 2052, 304.65,
     "Audio recordings of sermons and teachings. NOTE: May be a symlink or duplicate of sermons/ and homilies/ directories (identical file count and size).",
     "placeholder"),
    ("bak", 19, 0.10,
     "Backup files from the legacy site. May contain older versions of pages.",
     "placeholder"),
    ("banners", 29, 0.18,
     "Banner images and graphics used on the website.",
     "placeholder"),
    ("bulletin", 22, 0.10,
     "Parish bulletins — weekly or periodic publications for the congregation.",
     "placeholder"),
    ("calendar", 91, 8.20,
     "Orthodox liturgical calendar data. Includes daily saints, feastdays, and scripture readings.",
     "placeholder"),
    ("catechism", 210, 42.07,
     "Catechesis materials — Orthodox Christian teaching for inquirers and converts. Includes talks, essays, and educational resources on Orthodox theology, dogma, and practice.",
     "placeholder"),
    ("charities", 24, 0.13,
     "Information about charitable works and organizations supported by the parish.",
     "placeholder"),
    ("church-school", 9, 0.70,
     "Church school materials for children's religious education.",
     "placeholder"),
    ("churchyear", 24, 0.13,
     "Overview of the Orthodox liturgical year — major feasts, fasting seasons, and commemorations.",
     "placeholder"),
    ("confess", 65, 19.80,
     "Materials on the Sacrament of Confession (Holy Repentance) — preparation guides, teachings, and related content.",
     "placeholder"),
    ("conversions", 27, 0.17,
     "Conversion stories and testimonies of people who came to Orthodox Christianity.",
     "placeholder"),
    ("cotc", 69, 0.30,
     "COTC (Catechism of the Orthodox Tewahedo Church) or related catechetical content.",
     "placeholder"),
    ("dailylent", 69, 1.49,
     "Daily Lenten reflections and readings for the Great Lent season.",
     "placeholder"),
    ("daniel", 81, 48.07,
     "Content related to the Prophet Daniel or a contributor named Daniel. Includes substantial media files.",
     "placeholder"),
    ("data", 49, 2.71,
     "Data files used by the website — indexes, configuration files, and generated content.",
     "placeholder"),
    ("directory", 112, 0.77,
     "Directory listings and file indexes for various sections of the site.",
     "placeholder"),
    ("docs", 28, 1.12,
     "Miscellaneous documents — Word documents, PDFs, and other downloadable files.",
     "placeholder"),
    ("documents", 22, 0.25,
     "Additional documents and downloadable resources.",
     "placeholder"),
    ("doyouhaveaminute", 8, 0.13,
     "'Do You Have a Minute?' — short devotional readings and reflections.",
     "placeholder"),
    ("dyptichs", 28, 0.19,
     "Dyptichs — lists of hierarchs and commemorations used in Orthodox liturgical services.",
     "placeholder"),
    ("ecumenism", 40, 0.38,
     "Materials on ecumenism from an Orthodox Christian perspective — theological discussions and position papers.",
     "placeholder"),
    ("exact", 25, 0.82,
     "Content related to 'An Exact Exposition of the Orthodox Faith' by St. John of Damascus — a foundational work of Orthodox dogmatic theology.",
     "placeholder"),
    ("falbum", 29, 0.21,
     "Photo album or family album content.",
     "placeholder"),
    ("faq", 39, 0.58,
     "Frequently Asked Questions about Orthodox Christianity and the parish.",
     "placeholder"),
    ("fathers", 29, 0.70,
     "Patristic texts — writings of the Holy Fathers of the Orthodox Church, including St. John of Damascus's 'Exact Exposition of the Orthodox Faith'.",
     "placeholder"),
    ("forms", 7, 0.60,
     "Downloadable forms — membership forms, sacrament request forms, and other parish paperwork.",
     "placeholder"),
    ("full-voice", 312, 50.03,
     "'A Priest Must Speak With a Full Voice' — a collection of sermons, commentaries, and teachings by Fr. Seraphim Holland. Available in HTML, DOC, PDF, and audio formats.",
     "placeholder"),
    ("gleanings", 2242, 23.13,
     "Gleanings from Orthodox Christian Authors and the Holy Fathers — over 5,700 short texts organized alphabetically by topic. One of the largest sections of the site.",
     "placeholder"),
    ("goodtoknow", 2, 0.12,
     "'Good to Know' — brief informational pieces about Orthodox Christian life and practice.",
     "placeholder"),
    ("graphics", 27, 0.26,
     "Graphics, icons, and decorative images used throughout the site.",
     "placeholder"),
    ("greatlent", 163, 15.82,
     "Materials for the Great Lent season — sermons, reflections, prayers, liturgical texts, and fasting guidance for the most significant fasting period in the Orthodox calendar.",
     "placeholder"),
    ("guestbook", 25, 0.18,
     "Legacy guestbook — visitor messages and comments from the early website.",
     "placeholder"),
    ("hm", 21, 0.17,
     "HierMenus or related navigation/menu scripts from the legacy site.",
     "placeholder"),
    ("holiness-happens", 30, 0.31,
     "'Holiness Happens' — a series of spiritual reflections and teachings.",
     "placeholder"),
    ("holyweek", 31, 0.28,
     "Holy Week materials — liturgical texts, reflections, and guides for the week before Pascha (Easter).",
     "placeholder"),
    ("homilies", 2052, 304.65,
     "Homilies (sermons) collection. NOTE: May be a symlink or duplicate of sermons/ and audio/ directories (identical file count and size).",
     "placeholder"),
    ("ikons", 617, 92.97,
     "Collection of Orthodox Christian icons (ikons) — sacred images of Christ, the Theotokos, saints, and feastdays. Includes high-resolution scans and photographs.",
     "placeholder"),
    ("images", 138, 15.26,
     "General website images — photos, graphics, and visual assets used across the site.",
     "placeholder"),
    ("includes", 25, 0.21,
     "Server-side include files — shared HTML fragments (headers, footers, navigation) used by the legacy SSI-based site.",
     "placeholder"),
    ("journal", 420, 272.07,
     "Parish journal — extended writings, reflections, and pastoral commentary. One of the largest content sections by file size.",
     "placeholder"),
    ("js", 44, 0.27,
     "Legacy JavaScript files used by the old site.",
     "placeholder"),
    ("last-upload.all", 19, 0.18,
     "Records of the last FTP upload batch — used by the legacy Perl-based deployment system.",
     "placeholder"),
    ("legacy.orthodox.net", 1, 0.00,
     "Marker or redirect for the legacy site subdomain.",
     "placeholder"),
    ("letters", 39, 4.15,
     "Pastoral letters and correspondence.",
     "placeholder"),
    ("links", 76, 0.77,
     "Links to other Orthodox Christian websites, resources, and organizations.",
     "placeholder"),
    ("local-media", 1798, 20526.53,
     "Local media files — audio recordings of sermons, talks, and services. This is the largest directory (~20 GB) and will be archived in a separate repository.",
     "placeholder"),
    ("memorization", 26, 0.22,
     "Scripture memorization aids and resources.",
     "placeholder"),
    ("menaion", 766, 3.83,
     "The Menaion — liturgical texts organized by month for the fixed cycle of Orthodox feasts and saints' commemorations. This is the main index; monthly sub-directories contain individual entries.",
     "placeholder"),
    ("menaion-april", 200, 1.61, "Menaion entries for April.", "placeholder"),
    ("menaion-august", 214, 1.70, "Menaion entries for August.", "placeholder"),
    ("menaion-december", 212, 1.88, "Menaion entries for December.", "placeholder"),
    ("menaion-february", 183, 1.48, "Menaion entries for February.", "placeholder"),
    ("menaion-january", 213, 1.75, "Menaion entries for January.", "placeholder"),
    ("menaion-july", 222, 1.80, "Menaion entries for July.", "placeholder"),
    ("menaion-june", 215, 1.73, "Menaion entries for June.", "placeholder"),
    ("menaion-march", 190, 1.55, "Menaion entries for March.", "placeholder"),
    ("menaion-may", 203, 1.62, "Menaion entries for May.", "placeholder"),
    ("menaion-november", 253, 2.15, "Menaion entries for November.", "placeholder"),
    ("menaion-october", 216, 1.74, "Menaion entries for October.", "placeholder"),
    ("menaion-september", 318, 2.65, "Menaion entries for September.", "placeholder"),
    ("menaion-thoughts", 23, 0.23,
     "Meditations on the Saints — daily reflections tied to the Menaion calendar.",
     "placeholder"),
    ("menu", 42, 0.32,
     "Legacy navigation menu files — JavaScript-based dropdown menus from the old site design.",
     "placeholder"),
    ("microbiology", 24, 0.29,
     "Content related to microbiology — possibly from a contributor or a personal interest page hosted on the site.",
     "placeholder"),
    ("ministries", 37, 1.87,
     "Parish ministries — descriptions of various service groups and outreach programs.",
     "placeholder"),
    ("misc", 51, 0.65,
     "Miscellaneous files that don't fit into other categories.",
     "placeholder"),
    ("moleben", 20, 0.30,
     "Moleben (Molieben) — intercessory prayer services used in Orthodox worship.",
     "placeholder"),
    ("monastic-stories", 25, 0.26,
     "Stories from monastic life — accounts of monks, nuns, and monastic communities in the Orthodox tradition.",
     "placeholder"),
    ("music", 54, 1.38,
     "Orthodox church music — sheet music, audio recordings, and resources for liturgical singing.",
     "placeholder"),
    ("nativity", 69, 1.02,
     "Materials for the Nativity season (Christmas) — sermons, hymns, reflections, and liturgical texts.",
     "placeholder"),
    ("news", 35, 1.24,
     "News items and updates related to the parish or the broader Orthodox community.",
     "placeholder"),
    ("newsletter", 26, 0.32,
     "Parish newsletters — periodic publications with parish news, teaching, and community updates.",
     "placeholder"),
    ("onet", 889, 14.38,
     "ONET (Orthodox Net) site infrastructure files — templates, scripts, and configuration from the legacy site management system.",
     "placeholder"),
    ("osb", 49, 0.94,
     "Orthodox Study Bible resources or related content.",
     "placeholder"),
    ("pascha", 114, 2.51,
     "Pascha (Easter) materials — the central feast of the Orthodox Christian year. Includes Paschal hymns, sermons, liturgical texts, and reflections in English and Church Slavonic.",
     "placeholder"),
    ("pastoral-commentary-on-the-psalms", 19, 0.26,
     "Pastoral commentary on the Psalms — Fr. Seraphim Holland's reflections on the Book of Psalms.",
     "placeholder"),
    ("photos", 516, 316.90,
     "Parish photographs — church events, services, parish life, and community gatherings. Large collection (~317 MB), may be archived in a separate repository.",
     "placeholder"),
    ("pilot", 24, 0.28,
     "Pilot or prototype pages — early versions or test pages.",
     "placeholder"),
    ("podcasts", 129, 1.84,
     "Podcast content — audio teachings and talks distributed as podcasts.",
     "placeholder"),
    ("poetry", 29, 0.30,
     "Orthodox Christian poetry — original poems and collected verse.",
     "placeholder"),
    ("prayers", 26, 0.29,
     "Prayer texts — morning and evening prayers, prayer rules, and other devotional prayers.",
     "placeholder"),
    ("prison-ministry", 350, 86.72,
     "Prison ministry materials — resources, correspondence, and content from the parish's outreach to incarcerated individuals.",
     "placeholder"),
    ("prisonministry", 4, 0.03,
     "Additional prison ministry content (possibly older or alternate location).",
     "placeholder"),
    ("private_", 1, 20.07,
     "Private files — restricted content. Contains a single large file (~20 MB).",
     "placeholder"),
    ("prologue", 802, 6.60,
     "The Prologue from Ohrid — daily readings from the classic Orthodox devotional by St. Nikolai Velimirovich, organized by date.",
     "placeholder"),
    ("questions", 473, 6.58,
     "Orthodoxy Questions and Answers — responses to common and detailed questions about Orthodox Christian faith, practice, and theology.",
     "placeholder"),
    ("questions2", 104, 1.78,
     "Additional questions and answers — continuation or second series of the Q&A section.",
     "placeholder"),
    ("quiz", 275, 2.29,
     "Orthodox Christian quizzes — interactive or printable quizzes on theology, scripture, and church history.",
     "placeholder"),
    ("recipes", 65, 0.60,
     "Fasting recipes and cooking resources — recipes suitable for Orthodox fasting periods.",
     "placeholder"),
    ("redeeming", 99, 3.82,
     "Redeeming the Time — related content or alternate location for the blog/journal.",
     "placeholder"),
    ("redeemingthetime", 3434, 125.19,
     "'Redeeming the Time' — Fr. Seraphim Holland's blog and journal. One of the largest sections, containing years of regular writings, reflections, and pastoral commentary.",
     "placeholder"),
    ("redeemingthetime.backup", 19, 0.30,
     "Backup of the Redeeming the Time blog content.",
     "placeholder"),
    ("referenc", 24, 0.32,
     "Reference materials — glossaries, indexes, and reference resources for Orthodox Christianity.",
     "placeholder"),
    ("roc", 30, 0.40,
     "Russian Orthodox Church — materials related to the ROC, its history, hierarchy, and teachings.",
     "placeholder"),
    ("roca", 32, 0.45,
     "Russian Orthodox Church Abroad (ROCA/ROCOR) — materials related to the church body that St. Nicholas parish belongs to.",
     "placeholder"),
    ("rubrics", 68, 0.93,
     "Liturgical rubrics — instructions for the conduct of Orthodox worship services.",
     "placeholder"),
    ("russia", 35, 0.41,
     "Materials related to Russia — history, saints, and the Russian Orthodox tradition.",
     "placeholder"),
    ("russiannm", 260, 6.05,
     "Russian New Martyrs — lives of saints who were martyred during the Soviet persecution of the Orthodox Church in Russia.",
     "placeholder"),
    ("saints", 45, 2.38,
     "Lives of Saints — hagiographies (biographies of saints), particularly New Martyrs, Hieromartyrs, and Confessors of Russia.",
     "placeholder"),
    ("scripture", 188, 8.71,
     "Daily Scripture Readings and Reflections — commentary on the daily epistle and gospel readings from the Orthodox lectionary.",
     "placeholder"),
    ("scripture-memory", 111, 2.69,
     "Scripture memorization program — organized sets of Bible verses for memorization.",
     "placeholder"),
    ("search", 25, 0.33,
     "Search functionality files for the legacy site.",
     "placeholder"),
    ("september-11-2001", 35, 0.46,
     "Materials related to September 11, 2001 — reflections, prayers, and responses from an Orthodox Christian perspective.",
     "placeholder"),
    ("sermon-notes", 44, 1.22,
     "Sermon notes — outlines and study notes accompanying sermon audio recordings.",
     "placeholder"),
    ("sermons", 2052, 304.65,
     "Sermons (homilies) — the primary collection of Gospel and Epistle homilies and other sermons by Fr. Seraphim Holland. Available in HTML, DOC, PDF, and audio formats. NOTE: May share content with homilies/ and audio/ directories.",
     "placeholder"),
    ("sermons-index", 25, 0.40,
     "Sermon index pages — navigational indexes for the sermon collection, organized by date, topic, and scripture reference.",
     "placeholder"),
    ("services", 370, 72.74,
     "Orthodox liturgical services — full texts of Divine Liturgy, Vespers, Matins, and other services in English and Church Slavonic.",
     "placeholder"),
    ("slicebox", 68, 0.90,
     "Slicebox — a 3D image slider library used on the legacy site.",
     "placeholder"),
    ("slides-slidesjs-3", 66, 3.43,
     "SlidesJS — image slideshow library and content used on the legacy site.",
     "placeholder"),
    ("stnicholas", 245, 10.02,
     "St. Nicholas content — materials about the patron saint of the parish, St. Nicholas the Wonderworker, including icons, lives, miracles, and feast day materials.",
     "placeholder"),
    ("synaxarion", 25, 0.37,
     "Synaxarion — brief lives of saints read during Orthodox liturgical services.",
     "placeholder"),
    ("talks", 19, 0.34,
     "Talks and lectures on Orthodox Christian topics.",
     "placeholder"),
    ("templates", 8, 0.03,
     "HTML templates used by the legacy site's page generation system (Perl-based make_html.pl).",
     "placeholder"),
    ("theophany", 31, 0.42,
     "Theophany (Epiphany) materials — sermons, hymns, and liturgical texts for the Feast of Theophany, commemorating Christ's baptism in the Jordan.",
     "placeholder"),
    ("tidy", 19, 0.36,
     "HTML Tidy output — cleaned versions of legacy HTML files.",
     "placeholder"),
    ("topics", 30, 0.43,
     "Topic index — cross-references and topical organization of content across the site.",
     "placeholder"),
    ("tothinkabout", 73, 0.85,
     "'To Think About' — short reflections and thought-provoking spiritual readings.",
     "placeholder"),
    ("trebnic", 369, 54.66,
     "Trebnic (Book of Needs) — prayers and services for various occasions: blessings, prayers for the sick, funeral services, house blessings, and other occasional services.",
     "placeholder"),
    ("troparia", 28, 0.42,
     "Troparia and kontakia — short hymns for saints and feasts used in Orthodox worship.",
     "placeholder"),
    ("txt", 1, 0.41,
     "Plain text files.",
     "placeholder"),
    ("ustav", 117, 1.65,
     "Typicon (Ustav) — the liturgical rule book governing the order of Orthodox worship services, fasting regulations, and calendar observances.",
     "placeholder"),
    ("western-saints", 40, 0.61,
     "Western Saints — lives of Orthodox saints from Western Europe (Great Britain, Ireland, France, Norway, and more) who lived before the Great Schism of 1054.",
     "placeholder"),
    ("whatsnew", 29, 3.10,
     "'What's New' — announcements of newly added content to the site.",
     "placeholder"),
    ("wpt-3", 3434, 132.28,
     "WordPress backup or export — appears to be a WordPress installation or content export (possibly from Redeeming the Time blog).",
     "placeholder"),
]


def main():
    os.makedirs(BASE, exist_ok=True)

    for dirname, file_count, size_mb, description, status in DIRECTORIES:
        dirpath = os.path.join(BASE, dirname)
        os.makedirs(dirpath, exist_ok=True)

        if dirname == "local-media":
            repo_note = "\n\n> **This directory will be archived in a separate repository** (`orthodox-net-archive-media`) due to its size (~20 GB).\n"
        elif dirname == "photos":
            repo_note = "\n\n> **This directory may be archived in a separate repository** (`orthodox-net-archive-photos`) due to its size (~317 MB).\n"
        else:
            repo_note = "\n"

        readme = f"""# {dirname}/

{description}
{repo_note}
## Server inventory

- **Files**: {file_count:,}
- **Size**: {size_mb} MB
- **Status**: {'Placeholder — content not yet downloaded' if status == 'placeholder' else 'Content archived'}
- **Source**: `https://www.orthodox.net/{dirname}/`

## Original URL

`https://www.orthodox.net/{dirname}/index.html`
"""
        with open(os.path.join(dirpath, "README.md"), "w") as f:
            f.write(readme)

    # Write the top-level public_html README
    with open(os.path.join(BASE, "README.md"), "w") as f:
        f.write("""# public_html/

This directory mirrors the file structure of `https://www.orthodox.net` as hosted on the Inoa/Orthodox Internet Services server at `/home/nicholas/public_html/`.

Each subdirectory corresponds to a content section on the orthodox.net website. README files in each directory describe the contents and current archive status.

## Inventory summary

- **Total directories**: %d
- **Total files on server**: ~22,600
- **Total size on server**: ~22 GB (of which ~20 GB is local-media/)
- **Inventory date**: 2026-03-22

## Directories excluded from this archive

| Directory | Reason |
|-----------|--------|
| `new/` | Contains onet-v2, already on GitHub |
| `.well-known/` | SSL certificate validation |
| `cgi-bin/` | Server scripts |
| `dev/`, `exercise/`, `haiti/`, `pentecostarion/`, `seraphim/` | Empty directories |
| `wpt/`, `wpt-j/`, `wpt-w/` | WordPress test artifacts |
""" % len(DIRECTORIES))

    print(f"Created {len(DIRECTORIES)} directories with READMEs in {BASE}")


if __name__ == "__main__":
    main()
